
- hosts: temp
  vars:
    test: "{|hostname|:|{{ansible_hostname}}|, |IP|:|{{ansible_all_ipv4_addresses}}|, |sistema|:|{{ansible_system}}|, |distribucion|:|{{ansible_distribution}} {{ansible_distribution_version}}|, |arquitectura_version|:|{{ansible_architecture}}| , |procesador|:|{{ansible_processor}}|, |cores|:|{{ansible_processor_cores}}|, |cores_count|:|{{ansible_processor_count}}| , |cores_virtual|:|{{ansible_processor_vcpus}}|, |memoria|:|{{ansible_memtotal_mb}}|,|memoria_swap|:|{{ansible_swaptotal_mb}}|, |kernel|:|{{ansible_kernel}}|, |ver_bios|:|{{ansible_bios_version}}|, |interfaces_red|:|{{ansible_interfaces}}|, |virtual|:|{{ansible_product_name}}|,|python|:|{{ansible_python_version}}|,|parsed|:|0|,|CurrentTimeZone|:|{{ansible_date_time.tz_offset}}| }"
    test2: "{|hostname|:|{{ansible_hostname}}|, |IP|:|{{ansible_all_ipv4_addresses}}|, |sistema|:|{{ansible_system}}|, |distribucion|:|{{ansible_distribution}}|, |distribucion_version|:|{{ansible_distribution_version}}|, |arquitectura_version|:|{{ansible_architecture}}| , |procesador|:|{{ansible_processor}}|, |cores|:|{{ansible_processor_cores}}|, |cores_count|:|{{ansible_processor_count}}|, |memoria|:|{{ansible_memtotal_mb}}|,|memoria_swap|:|{{ansible_swaptotal_mb}}|, |kernel|:|{{ansible_kernel}}|, |interfaces_red|:|{{ansible_interfaces}}|, |python|:|{{ansible_python_version}}|,|parsed|:|0|,|CurentTimeZone|:|{{ansible_date_time.tz_offset}}| }"
  tasks:
    - name: ejecucion local
      shell: /tmp/unix-2-es.py "{{test}}" "{{ansible_all_ipv4_addresses}}"
      delegate_to: localhost
      #when: (ansible_distribution == "RedHat" )

    - name: ejecucion local AIX
      shell: /tmp/unix-2-es.py "{{test2}}" "{{ansible_all_ipv4_addresses}}"
      delegate_to: localhost
      when: (ansible_distribution == "AIX" or ansible_distribution == "Solaris" )
